services:
  app:
    build: .
    depends_on:
      - mongo
    environment:
      - ENVIRONMENT=docker
    command: python src/etl.py
  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
